/*  EDOS – Case study catalogue
 *  Single source of truth for all case studies shown across the site.
 */
var CASES=[
{u:"/case-study/marketplace-musicisti-organizzatori/",t:"Marketplace per musicisti e conservatori",d:"I musicisti dei conservatori presentano il loro percorso, chi organizza un evento pubblica cosa gli serve e sceglie.",ty:"platform",se:"tech",sl:"Entertainment & Events",sv:"Gestionali su misura"},
{u:"/case-study/crm-b2c-richieste-mutuo/",t:"CRM B2C per mutui online",d:"Chi cerca un mutuo riceve subito una risposta, il consulente riceve una richiesta già completa.",ty:"platform",se:"finance",sl:"Finance / Banking",sv:"Project management"},
{u:"/case-study/piattaforma-instant-win-brand-energia/",t:"Piattaforma instant win per brand energia",d:"Un gioco a premi sulle partite dentro l’app di un fornitore di energia, collegato al sistema che decide le vincite.",ty:"platform",se:"energy",sl:"Energia & Promozioni",sv:"Gestionali su misura"},
{u:"/case-study/supporto-tecnico-piattaforma-no-profit/",t:"Supporto tecnico per piattaforma No-Profit internazionale",d:"Il sito per donare e l’area sostenitori di un programma di sostegno a distanza, presi in carico da un altro fornitore.",ty:"platform",se:"tech",sl:"No-Profit / Internazionale",sv:"Assistenza ed evoluzione"},
{u:"/case-study/sito-istituzionale-studio-professionale/",t:"Sito istituzionale per studio professionale",d:"Due studi notarili diventano uno: un sito che li presenta come una realtà sola e la posta su un unico dominio.",ty:"web",se:"finance",sl:"Studi professionali",sv:"Siti ed e-commerce"},
{u:"/case-study/ecommerce-b2b-network-franchising/",t:"E-commerce B2B per network franchising",d:"Una rete di affiliati con acquisti, contratti e fatturazione centralizzati in un’unica piattaforma.",ty:"ecommerce",se:"retail",sl:"Real Estate / Franchising",sv:"Siti ed e-commerce"},
{u:"/case-study/app-organizzazione-eventi-sportivi/",t:"App per organizzare partite sportive amatoriali",d:"App nativa iOS e Android per organizzare partite sportive amatoriali, gestire squadre e prenotare campi.",ty:"app",se:"tech",sl:"Sport & Tempo libero",sv:"App e web app"},
{u:"/case-study/piattaforma-ai-perizie-immobiliari/",t:"Piattaforma AI per perizie immobiliari",d:"Generazione assistita da AI delle relazioni peritali, da foto di sopralluogo a documento.",ty:"ai",se:"industry",sl:"Edilizia & Costruzioni",sv:"AI nelle pratiche"},
{u:"/case-study/gestionale-servizi-ncc-taxi/",t:"Gestionale per servizi NCC e taxi",d:"Turni, incassi, spese e stipendi soci in un unico sistema, in continua evoluzione.",ty:"platform",se:"tech",sl:"Trasporti & Mobilità",sv:"Gestionali su misura"},
{u:"/case-study/continuity-evolution-gruppo-multipiattaforma/",t:"Assistenza ed evoluzione per un gruppo multi-piattaforma",d:"Le piattaforme di un gruppo che segue le imprese su agevolazioni e crediti d’imposta, seguite ed estese dal 2025.",ty:"platform",se:"tech",sl:"Consulenza Strategica",sv:"Assistenza ed evoluzione"},
{u:"/case-study/piattaforma-gestionale-assicurativo/",t:"Pagina di bilancio per un gruppo assicurativo",d:"La pagina web bilingue del bilancio annuale di un gruppo assicurativo, aggiornata a ogni edizione.",ty:"platform",se:"finance",sl:"Assicurazioni",sv:"Assistenza ed evoluzione"},
{u:"/case-study/modulo-ecommerce-settore-farmaceutico/",t:"Modulo e-commerce per un'azienda farmaceutica",d:"Sviluppo di un canale e-commerce per un'azienda del settore chimico-farmaceutico. Progetto in corso.",ty:"ecommerce",se:"industry",sl:"Chimico & Farmaceutico",sv:"Siti ed e-commerce"},
{u:"/case-study/piattaforma-unica-pratiche-assicurative/",t:"Piattaforma unica per pratiche assicurative",d:"Un'agenzia assicurativa sostituisce due sistemi separati con un'unica piattaforma database-first. Progetto in corso.",ty:"platform",se:"finance",sl:"Assicurazioni",sv:"Gestionali su misura"},
{u:"/case-study/piattaforma-candidature-premio-ricerca/",t:"Piattaforma candidature per un premio scientifico",d:"Candidature in italiano e in inglese per il premio internazionale di una fondazione. Progetto in corso.",ty:"platform",se:"tech",sl:"Fondazioni & Ricerca",sv:"Gestionali su misura"},
{u:"/case-study/piattaforma-crm-vendite/",t:"Piattaforma CRM per vendite",d:"Riscrittura indipendente del CRM vendite, con pipeline a 9 stadi e motore di lavorazione esiti. Progetto in corso.",ty:"platform",se:"tech",sl:"Marketing & Vendite",sv:"Gestionali su misura"}
];
